### ISSUE TITLE
Level doesn't reset properly if you die after getting Skittles

### ISSUE THREAD

**Issue by LHERMAN5** [PaoVal/Ex-it#8]
"tested again and this time I died after I had Skittles in my grasp. The level didn't completely reset though. The switches were back on and Skittles was loose again, and the interaction halos were missing. After I clicked both the switches again, skittles disappeared. I went to the regular exit door and got the right dialogue for after getting Skittles, but I wasn't able to go to the hub from the right exit door (it just stopped after the dialogue). It didn't freeze, I was just trapped haha" -Vickey

**Comment by Eenna** [comment]
Skittles disappears from the top left when second switch is pressed.
